name: CICD

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Java 8 JDK
        uses: actions/setup-java@4.2.1
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Compilation
        run: |
          mvn package

      - name: Unit Tests
        run: |
          mvn test

      - name: Setup Java 17 JDK
        uses: actions/setup-java@4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          
    
