name: CICD

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Java 8 JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Compilation and Unit Tests
        run: |
          mvn clean package test

      - name: Setup Java 17 JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: SonarCloud Scaner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.organization=pipe-cruz \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.projectKey=Pipe-Cruz_microservicio-java \
          -Dsonar.branch.name=feature-ms-FelipeCruz-mensaje \
          #-Dsonar.qualitygate.wait=true

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: jinba7ittai
          password: ${{ secrets.DOCKER_PASS}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Build
        run: |
          docker build -t jinba7ittai/feature-ms-mensaje:latest .

      - name: Docker push
        run: |
          docker push jinba7ittai/feature-ms-mensaje:latest

          
        
          
    
